apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pgadmin-service
  name: pgadmin-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30081
  selector:
    app: pgadmin-deployment
  type: NodePort
status:
  loadBalancer: {}