---
# tasks file for pgadmin_role
- name: generate compose file pgadmin
  template:
    src: "pgadmin-compose.yaml.j2"
    dest: "/home/{{ ansible_user }}/pgadmin-compose.yaml"
    mode: "0555"
  tags: start

- name: start stack pgadmin
  command: "docker compose -f /home/{{ ansible_user }}/pgadmin-compose.yaml up -d"
  tags: start

- name: Stop stack pgadmin
  command: "docker compose -f /home/{{ ansible_user }}/pgadmin-compose.yaml down -v --remove-orphans"
  tags: delete

- name: Delete pgadmin compose file
  command: "rm -f /home/{{ ansible_user }}/pgadmin-compose.yaml"
  tags: delete